version: 2.1

orbs:
  slack: circleci/slack@4.1

slack/notify: &slack_notify
  branch_pattern: master
  event: fail
  channel: ci-build-status
  template: SLACK_TAG_CI_FAILURE_TEMPLATE

commands:
  export_slack_id:
    steps:
      - run:
          name  : Exporting circleci username as slack id.
          command: echo 'export SLACK_PARAM_MENTIONS="$CIRCLE_USERNAME"' >> "$BASH_ENV"
      - run:
          name : CircleCi To Slack user mapping.
          command: |
            echo $GITHUB_SLACK_USERMAPPING | base64 --decode > github_slack
            while read -r line || [[ -n $line ]];
            do
              [[ ${line//[[:space:]]/} =~ ^#.* || -z "$line" ]] && continue
              echo "$line" | tr "=" "\n" | while read -r key; do
              read -r value
              if [ "$CIRCLE_USERNAME" = "${key}" ]; then
                echo "export SLACK_PARAM_MENTIONS='<@${value}>'" >> $BASH_ENV
              fi
              done
            done < github_slack
            rm github_slack

jobs:
  build:
    docker:
      - image: circleci/openjdk:8

    working_directory: ~/repo

    environment:
      TERM: dumb
      GRADLE_OPTS: -Dorg.gradle.project.sonatypeUsername=username -Dorg.gradle.project.sonatypePassword=password

    steps:
      - checkout
      - export_slack_id
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew test

      - slack/notify:
          <<: *slack_notify

workflows:
  sift-java:
    jobs:
      - build:
          context:
            - slack-templates
            - slack_Oauth
            - Github_Slack_UserMapping
