name: Sift Java CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

env:
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  API_KEY: ${{ secrets.API_KEY }}
  GITHUBCLONEKEY: ${{ secrets.GITHUBCLONEKEY }}
  GRADLE_OPTS: -Dorg.gradle.project.sonatypeUsername=username -Dorg.gradle.project.sonatypePassword=password

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew dependencies

      - name: Gradle Test
        run: ./gradlew test

  java_integration:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      - run: |
          ./gradlew distZip

      - name: get version
        id: version
        run: |
          PROP_VALUE=`./gradlew properties -q | grep "version:" | cut -d'=' -f2`
          echo $PROP_VALUE
          echo "version=$PROP_VALUE" >> $env:GITHUB_ENV
          echo ${{ env.version }}

      - name: Clone sift-java-integration-app and extract sift-java
        uses: actions/checkout@v4
        with:
          repository: SiftScience/sift-java-integration-app
          ssh-key: ${{ secrets.GITHUBCLONEKEY }}
          ref: main
          path: /home/runner/work/sift-java/sift-java/

      - name: Build with Gradle Wrapper
        run: |
          ls
          unzip -j ../build/distributions/sift-java-3.14.2.zip -d app/libs/