name: Publishing to Sonatype
on:
  release:
    types: [published]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.362'
          distribution: 'zulu'
      - name: Prepare gradle.properties
        run: |
          echo -e "${{ secrets.SECRING }}" | base64 -d > ./secring.gpg         
          echo "signing.keyId=${{ secrets.KEYID }}" >> ./gradle/wrapper/gradle-wrapper.properties
          echo "signing.password=${{ secrets.PASS }}" >> ./gradle/wrapper/gradle-wrapper.properties
          echo "signing.secretKeyRingFile=./secring.gpg" >> ./gradle/wrapper/gradle-wrapper.properties
          echo "sonatypeUsername=${{ secrets.SUSER }}" >> ./gradle/wrapper/gradle-wrapper.properties
          echo "sonatypePassword=${{ secrets.SPASSWORD }}" >> ./gradle/wrapper/gradle-wrapper.properties
      - name: Prepare build.gradle
        run: |
          sed -i -e 's|.*sonatypeUsername.*|                username = "${{ secrets.SUSER }}"|' ./build.gradle 
          sed -i -e 's|.*sonatypePassword.*|                password = "${{ secrets.SPASSWORD }}"|' ./build.gradle 
      - name: Publish to Sonatype
        run: |
          ./gradlew publishJarPublicationToStagingRepository